CXX = g++
CXXFLAGS += -g -Wall -std=c++11 -pedantic

CAIRO_FLAGS = $(shell pkg-config --cflags librsvg-2.0)
CAIRO_CXXFLAGS = $(if $(CAIRO_FLAGS),$(CAIRO_FLAGS),-DNO_CAIRO)

IMAGICK_FLAGS = $(shell GraphicsMagick++-config --cppflags --cxxflags)
IMAGICK_CXXFLAGS = $(if $(IMAGICK_FLAGS),$(IMAGICK_FLAGS),-DNO_IMAGICK)

CXXFLAGS += $(CAIRO_CXXFLAGS) $(IMAGICK_CXXFLAGS)

DRAW_LDFLAGS = $(shell pkg-config --libs librsvg-2.0)
DRAW_LDFLAGS += $(shell GraphicsMagick++-config --ldflags --libs)

LDFLAGS += $(DRAW_LDFLAGS)

.DEFAULT_GOAL := all

SOURCES = 
SOURCES += melangeur.cpp
SOURCES += couleurs.cpp
SOURCES += case.cpp
SOURCES += mur.cpp
SOURCES += site.cpp
SOURCES += direction.cpp
SOURCES += console_pad.cpp
SOURCES += draw.cpp

OBJECTS = $(SOURCES:.cpp=.o)

$(OBJECTS) : %.o : %.cpp
	$(CXX) -MMD $(CXXFLAGS) -c $< -o $@

CLEAN_OBJECTS = $(OBJECTS)
TARGETS = 

########## test_draw ##########

TEST_DRAW_SOURCES = test_draw.cpp
TEST_DRAW_OBJECTS = $(TEST_DRAW_SOURCES:.cpp=.o)

test_draw : $(TEST_DRAW_OBJECTS) $(OBJECTS) $(HEADERS)
	$(CXX) $(TEST_DRAW_OBJECTS) $(OBJECTS) -o $@ $(LDFLAGS)
	
$(TEST_DRAW_OBJECTS): %.o : %.cpp
	$(CXX) -MMD $(CXXFLAGS) -c $< -o $@

all : test_draw
TARGETS += test_draw
CLEAN_OBJECTS += $(TEST_DRAW_OBJECTS)

########## cleanup ##########
DEPS = $(CLEAN_OBJECTS:.o=.d)

clean:
	@rm -f $(DEPS) $(TARGETS) $(CLEAN_OBJECTS)

-include $(DEPS)
